"""adding bus table

Revision ID: f3bb3ef578d3
Revises: 6da0a94fad8f
Create Date: 2025-03-24 10:14:15.232612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3bb3ef578d3'
down_revision = '6da0a94fad8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bus_type')
    )
    op.add_column('users', sa.Column('email', sa.String(length=256), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(length=500), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'address')
    op.drop_column('users', 'email')
    op.drop_table('buses')
    # ### end Alembic commands ###
